### ISSUE TITLE
I have a problem at ./manage.py migrate --database meta 

### ISSUE THREAD

**Issue by magical-lhd** [strongswan/strongTNC#19]
hello!
I have a problem when running  ./manage.py migrate --database meta.
(django.db.utils.OperationalError: no such table : auth_permission.)
But   ./manage.py migrate can be successfully executed.

Then,I can't exxcuted ./manage.py setpassword.
   djiango.db.utils.OperationalError: no such table: auth_user.
my os : ubuntu 19.10

I am following the README.rst exactly, so I am very confused. Thank you！！！

**Comment by tobiasbrunner** [comment]
I pushed a possible fix to the _fix-migrate_ branch (74ec6348057bfec6ae20ddc1671ad1be1445b510).
